# Generated by Django 5.2.8 on 2026-03-03 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTemp',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=255)),
                ('story_content', models.TextField()),
                ('story_start', models.TextField()),
                ('story_setting_1', models.TextField()),
                ('story_setting_2', models.TextField(blank=True, null=True)),
                ('story_setting_3', models.TextField(blank=True, null=True)),
                ('story_setting_4', models.TextField(blank=True, null=True)),
                ('story_setting_5', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'db_table': 'story_temp',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('kid', 'Kid'), ('parent', 'Parent')], max_length=6)),
                ('user_name', models.CharField(max_length=63)),
                ('user_password', models.CharField(max_length=63)),
                ('user_status', models.CharField(choices=[('Y', 'Active'), ('N', 'Inactive'), ('L', 'Locked')], default='Y', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('user_story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_story_status', models.CharField(choices=[('Y', 'Active'), ('N', 'Inactive'), ('L', 'Locked')], default='Y', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(db_column='story_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='chatpj.storytemp')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='chatpj.usertable')),
            ],
            options={
                'verbose_name': 'user story',
                'verbose_name_plural': 'user stories',
                'db_table': 'user_story',
            },
        ),
        migrations.CreateModel(
            name='UserStoryEntry',
            fields=[
                ('user_story_entry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('entry_status', models.CharField(choices=[('Y', 'Active'), ('N', 'Inactive'), ('L', 'Locked')], default='Y', max_length=1)),
                ('entry_content', models.TextField()),
                ('entry_role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_story', models.ForeignKey(db_column='user_story_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='chatpj.userstory')),
            ],
            options={
                'verbose_name': 'user story entry',
                'verbose_name_plural': 'user story entries',
                'db_table': 'user_story_entry',
            },
        ),
    ]
