# Generated by Django 5.2.8 on 2026-03-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storytemp',
            name='story_description',
            field=models.CharField(default='', max_length=1023),
        ),
        migrations.AddField(
            model_name='storytemp',
            name='story_status',
            field=models.CharField(choices=[('Y', 'Active'), ('N', 'Inactive'), ('L', 'Locked')], default='Y', max_length=6),
        ),
        migrations.AddField(
            model_name='storytemp',
            name='story_tag_1',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='storytemp',
            name='story_tag_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='storytemp',
            name='story_tag_3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userstoryentry',
            name='entry_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storytemp',
            name='story_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='user_story_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userstoryentry',
            name='user_story_entry_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
